### ISSUE TITLE
Expand on JSON configuration file validation errors

### ISSUE THREAD

**Issue by bladedeyna** [svenheden/csharp-models-to-typescript#2]
**csharp-models-to-typescript version: "0.6.0"**

The JSON configuration file validator simply says that the JSON is invalid. It would be useful if it expanded on which line is invalid to help debugging issues in the configuration file.

![invalidjson](https://user-images.githubusercontent.com/24935514/38881158-542af17c-425f-11e8-9527-92de6d14bd2e.png)

**Comment by mfogliatto** [comment]
Maybe it's something different in your case, but I ran into the same issue and it was an encoding problem.
If you check the source code you'll notice that the file is expected to be in utf-8 (no bom), so make sure your config file is using that format.

**Comment by svenheden** [comment]
Sorry for the delay, but this has now been fixed in v0.17.1. Thanks for your feedback!
