### ISSUE TITLE
Use records instead of object with typed key accessors

### ISSUE THREAD

**Issue by AdnanDervisevic** [svenheden/csharp-models-to-typescript#30]
Hey,

Been running into the issue since I upgraded typescript of: An index signature parameter type cannot be a union type. Consider using a mapped object type instead.ts(1337)

This is for a case like
`ArbitraryMember: { [key: Enum]: Object };`

where I am no longer allowed to use the Enum or a Type Alias even. This is quite annoying in our project since we rely on that a lot, especially type aliases. There's a pretty nice and easy fix though, which is to use the Record type.

The aboev case would be then:
`ArbitraryMember: Record<Enum, Object>`

Which is imo a pretty nice type, very usable with intellisense and fits very well for what we're trying to actually accomplish here, which is to match a dictionary type or in javascript an object with a key index accessor. This has worked great in all the situations I've tried it, including stuff like

 `Member: Record<string, boolean>` which is then used as `true && this.object.member["customerId"]`.

The only drawback I can see is that Record is not backwards compatible past TypeScript 2.1 but I'm not sure that's a big deal? Could be opt-in if that's the case. I'll make a PR if you don't disagree with this, or we can discuss alternate solutions :)

**Comment by svenheden** [comment]
Good idea, thanks!

**Comment by pedrodbsa** [comment]
Really cool, I was unaware of the Record type. 

There's just one small issue with this MR. If the class descends from a collection type, the generation produces invalid typescript. Example:

```csharp
public class Foo : Dictionary<string, bool> { }
```
outputs:

```typescript
export interface Foo {
     Record<string, boolean>;
}
```
