### ISSUE TITLE
Implement an Enumeration base class

### ISSUE THREAD

**Issue by wzuqui** [svenheden/csharp-models-to-typescript#38]
I had to implement the DDD development standard (https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types), I made a fork and some changes. It would be great if we made a pull request. Thank you very much in advance.

https://github.com/wzuqui/ravex-csharp-models-to-json

**Comment by svenheden** [comment]
This is out of scope for this module, but thanks for your comment.

Would be nice if you included a reference to this project in your fork!
