### ISSUE TITLE
I'm getting 'Error: EISDIR: illegal operation on a directory'

### ISSUE THREAD

**Issue by omneimneh** [svenheden/csharp-models-to-typescript#40]
**Error upon running:**  `csharp-models-to-typescript --config=csharp.config.json`
```
{ [Error: EISDIR: illegal operation on a directory, open '<Dir>\src\models\input']
  errno: -4068,
  code: 'EISDIR',
  syscall: 'open',
  path: '<Dir>\\src\\models\\input' }
```
**csharp.config.json**
```
{
    "include": [
        "../<Dir>/InputModels/**/*.cs"
    ],
    "exclude": [],
    "namespace": "Api",
    "output": "./src/models/input",
    "camelCase": false,
    "camelCaseEnums": false,
    "numericEnums": false,
    "stringLiteralTypesInsteadOfEnums": false,
    "customTypeTranslations": {}
}
```
I also tried running this command as administrator in case something is wrong with the file permissions and gave everyone full control to this folder and I'm still getting the same error.

![issue](https://user-images.githubusercontent.com/49276638/76524912-8db9c480-6473-11ea-9e08-c0e4ed59c40f.png)

**Comment by omneimneh** [comment]
I just figured the output should be a file not a directory. Is there any option to output one file per .cs file?

**Comment by svenheden** [comment]
Unfortunately not @omneimneh
