### ISSUE TITLE
Allow camelcase options to be defined in config.

### ISSUE THREAD

**Issue by glhoest** [svenheden/csharp-models-to-typescript#50]
First of all, thank you for this awesome package.
I've been using it to great effect at one of the companies I work for.

Now I wanted to use it in another project, yet had to abort due to a conflict with the default camelcase options.
I could not use the package without having to change our public api to conform to the types this package emits.
Needless to say, that is not an acceptable option.

I think the solution would be quite simple.
Allow for the camelcase options object to be defined in the config json, and pass it through to where camelcase is used.
This should not result in any breaking changes.

**Comment by svenheden** [comment]
Thanks for the suggestion and PR @glhoest! It's released in v0.20.0 now.
