### ISSUE TITLE
Cannot find Namespace 'Api'

### ISSUE THREAD

**Issue by giv86** [svenheden/csharp-models-to-typescript#72]
after creating file
config-typegen.json:

`{
    "include": [
        "../DBO/**/*.cs"
    ],
    "exclude": [
    ],
    "namespace": "Api",
    "output": "./api.d.ts",
    "camelCase": false,
    "camelCaseEnums": false,
    "camelCaseOptions": {
        "pascalCase": false,
        "preserveConsecutiveUppercase": false,
        "locale": "en-US"
    },
    "numericEnums": false,
    "omitFilePathComment": false,
    "omitSemicolon": false,
    "stringLiteralTypesInsteadOfEnums": false,
    "customTypeTranslations": {
        "ProductName": "string",
        "ProductNumber": "string"
    }
}
`

and adding `   "generate-types": "csharp-models-to-typescript --config=config-typegen.json"` into `package.json`

whenever im trying to invoke model fom 'Api' i'm receiving `error TS2503: Cannot find namespace 'Api'.`

**Comment by giv86** [comment]
Yeah so... config file should like little bit different so it can work out of the box...
`
{
    "include": [
        "../DBO/**/*.cs"
    ],
    "exclude": [
    ],
    "namespace": null,
    "output": "src/models/apitypes.ts",
    "camelCase": false,
    "camelCaseEnums": false,
    "camelCaseOptions": {
        "pascalCase": false,
        "preserveConsecutiveUppercase": false,
        "locale": "en-US"
    },
    "numericEnums": false,
    "omitFilePathComment": false,
    "omitSemicolon": false,
    "stringLiteralTypesInsteadOfEnums": false,
    "customTypeTranslations": {
        "ProductName": "string",
        "ProductNumber": "string"
    }
}`

**Comment by digocesar** [comment]
Hi @giv86. It has been fixed at release 1.0.0.
